# NAVIGATION MENU CONFIGURATION
# To link to homepage sections, use: /#section-id
# To link to pages, use: /page-name/ 
# Weight determines display order (lower numbers appear first)

main:
  # HOME: Links to homepage (content/_index.md)
  - name: Home
    url: /
    weight: 10
  # PAPERS: Links to #papers section on homepage  
  - name: Papers
    url: /#papers
    weight: 11
  # TALKS: Links to #talks section on homepage
  - name: Talks
    url: /#talks
    weight: 12
  # NEWS: Links to #news section on homepage
  - name: News
    url: /#news
    weight: 13
  # CV: Links to experience page (content/experience.md)
  - name: CV
    url: experience/
    weight: 20
  # TOOLS: Links to tools page (content/tools/index.md)
  - name: Tools
    url: tools/
    weight: 25
  # POSTS: Links to posts page (content/posts.md)  
  - name: Posts
    url: /posts/
    weight: 30
  # - name: Works
  #   url: Works/
  #   weight: 40
#  - name: Teaching
#    url: teaching/
#    weight: 40
